### ISSUE TITLE
savable code blocks

### ISSUE THREAD

**Issue by naman-msft** [Azure/InnovationEngine#224]
which would enable codeblocks of the type YAML, JSON, etc. to be auto-saved in the current working directory of the exec doc during runtime. The syntax for doing something like this would look like this in an exec-doc:
 
 
```markdown
```yaml save-as=hello-world-enclave.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
...YAML CONTENT...
```
 
In the same line where the codeblock type is specified yaml, you would give the codeblock an attribute save-as=<file-name>  and this would then allow that particular code blocks to be auto-saved by innovation engine in that working directory - without spoiling the way the code looks in the source doc. 

It wouldn't solve the issue where files external to the document are referenced but not present during execution, but it would allow for documents to use codeblocks as a mechanism to create files and that can then be referenced by commands in the document.
 
This would make it easier to deploy exec docs via terraform, OpenTofu, Pulumi, and other deployment mechanisms besides standard markdown

**Comment by rgardler-msft** [comment]
This feels like scope creep. The goal of IE is to NOT add requirements on document authors for a document to be executable. This adds such a requirement.

Since code blocks should already be marked up with their type (e.g. `yaml`) we can infer that this is supposed to be saved and simply go ahead and do it in a temp directory. The location of this file can be stored in an environment variable and used automatically. e.g.

When exporting the script we simply inject the code to save to that file a so even when running from exported script the result is the same.

**Comment by rgardler-msft** [comment]
Closing as `Won't Fix`. If the proposed solution doesn't work for a given scenario then please provide a repro for that scenario and re-open.
