### ISSUE TITLE
Values of environment variables are not available in the console after completion

### ISSUE THREAD

**Issue by rgardler-msft** [Azure/InnovationEngine#64]
Some environment variables are set during script execution, e.g. FQDN. These are not copied into the environment for the console. This means that when control is provided to the user they no longer have access to those values.

In some scenarios this is not a big deal, e.g. when SSHd into a VM just created. In others they are important, e.g. when working with an AKS cluster.

**Comment by vmarcella** [comment]
We are unable to expose the environment variables set during the execution of `ie ` to the parent environment because the environment variables are scoped to the lifetime of ie. We can however preserve the environment variables by creating a file that stores the environment variables set by a scenario and then having the portal immediately source that command right after the command (But only if it succeeds). The overall command that the portal would have to execute would look like this:

```bash
ie execute <rest of ie params> && source /tmp/env-vars
```

**Comment by mbifeld** [comment]
Integrated on Portal side

**Comment by vmarcella** [comment]
This has been fixed in #20 and the environment is now preserved after a scenario executes in the portal:
 
![MicrosoftTeams-image](https://github.com/Azure/InnovationEngine/assets/6026326/94092143-e20a-4e54-bc23-ad60d9d0ada2)
